[project]
name = "expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ahamed sha", email = "iahamedsha@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.4",
    "sqlalchemy>=2.1.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
expense-tracker = "expense_tracker.main:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
